# Writes one C++ header that holds each builtin Slang module as a byte array. The cooker loads the
# modules from memory, so mussing about with search paths or embedding these as source strings
# is necessary: additionally, these should update and account for edits in the input files
# used to build the output header.
#
# Run in script mode:
#   cmake -DOUTPUT=<header> -DSOURCES=<file|file|...> -P EmbedBuiltins.cmake
#
# The module name is the file stem. Each array ends with a zero byte, so the array is also a C string.
# `SourceSize` does not count that byte. These can be viewed or wrapped with string_view

if (NOT DEFINED OUTPUT OR NOT DEFINED SOURCES)
    message(FATAL_ERROR "EmbedBuiltins.cmake needs OUTPUT and SOURCES")
endif()

string(REPLACE "|" ";" source_list "${SOURCES}")
list(SORT source_list)

set(arrays "")
set(entries "")
foreach (source_path IN LISTS source_list)
    get_filename_component(module_name "${source_path}" NAME_WE)
    get_filename_component(file_name "${source_path}" NAME)
    file(SIZE "${source_path}" source_size)
    if (source_size EQUAL 0)
        message(FATAL_ERROR "EmbedBuiltins.cmake: ${source_path} is empty")
    endif()

    # CMake regex has no repeat count, so a loop writes 24 bytes to each line.
    file(READ "${source_path}" source_hex HEX)
    string(LENGTH "${source_hex}" hex_length)
    set(source_bytes "")
    set(offset 0)
    while (offset LESS hex_length)
        string(SUBSTRING "${source_hex}" ${offset} 48 hex_line)
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," byte_line "${hex_line}")
        string(APPEND source_bytes "    ${byte_line}\n")
        math(EXPR offset "${offset} + 48")
    endwhile()

    string(APPEND arrays
        "inline constexpr unsigned char k_${module_name}Source[] =\n{\n${source_bytes}    0x00\n};\n\n")
    string(APPEND entries
        "    EmbeddedBuiltinModule{ \"${module_name}\", \"${file_name}\", k_${module_name}Source, ${source_size}u },\n")
endforeach()

list(LENGTH source_list module_count)

set(header "// Generated by cmake/EmbedBuiltins.cmake from builtins/. Do not edit.
#pragma once
#ifndef LODESTONE_EMBEDDED_BUILTIN_MODULES_HPP
#define LODESTONE_EMBEDDED_BUILTIN_MODULES_HPP
#include <array>
#include <cstddef>

namespace lodestone
{

struct EmbeddedBuiltinModule
{
    const char* ModuleName;
    const char* FileName;
    const unsigned char* Source;
    size_t SourceSize;
};

${arrays}inline constexpr std::array<EmbeddedBuiltinModule, ${module_count}u> k_EmbeddedBuiltinModules
{

${entries}};

} // namespace lodestone

#endif // !LODESTONE_EMBEDDED_BUILTIN_MODULES_HPP
")

# Write only on a change, so an unchanged builtin does not rebuild its includer.
if (EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous_header)
    if (previous_header STREQUAL header)
        return()
    endif()
endif()
file(WRITE "${OUTPUT}" "${header}")
